### ISSUE TITLE
`create-value-parser "array"` splits strings passed in body into characters

### ISSUE THREAD

**Issue by sbgreene1307** [zalando-stups/swagger1st#80]
With schema parameters like:
```
parameters:
      - in: "body"
        name: "body"
        description: "JSON array of words to add to the corpus"
        required: true
        schema:
          type: "object"
          required: 
          - words
          properties:
            words:
              type: "array"
              items:
                type: "string"
```

Sending a request like:
```
{"words":"foobar"}
```

The create-value-parser "array" will use the string value "foobar" since body is the first value in path. The subsequent map function applies the items-parser to each character of the string.

I would expect just the word "foobar" to be parsed since the default split array would be a csv split.
